### ISSUE TITLE
rotary encoder doesnt work properly

### ISSUE THREAD

**Issue by vishaltejwani** [Tommy-LSA/Arduino-Spotwelder#1]
https://www.youtube.com/watch?v=880_ICsn9AI

here is the video.

maybe try to use clickencoder.h?

rotary encoder isnt faulty checked on different code works fine

and instead of whitebackground a star or a dot looks better as a modification idea.

**Comment by Tommy-LSA** [comment]
Usage of a 10k Pullup resistor on A1 should fix that, if none is on your rotary encoder breakboard. There are breakouts in the wildlife which havn't tis pullup (see here https://www.letscontrolit.com/forum/viewtopic.php?t=6043 ) Also measure whether the switch pin of encoder is shorted to GND if pressed, to identify a hardware defect.

You also can test  changing line 368 to

`pinMode(KeySelect, INPUT_PULLUP);`

to use the internal pullup. BUT DON'T DO BOTH. Use only one pullup, external OR internal. 

The used libraries work fine for me. I have finished this project, so I'll not change things anymore. Feel free to clone the code and improve it.
